### ISSUE TITLE
Add access to other extension custom datafields

### ISSUE THREAD

**Issue by lockevod** [hammerheadnav/karoo-ext#18]
The extesions are very useful, we can create custom fields but it can be a great option if we can access to other custom typeid we create in other extensions (for example if we want to use headwind, a custom field that one github user are developing now)  then we won't have to copy the code (less compute, memory etc)

Regards

**Comment by brentnd** [comment]
`StartStreaming` takes a `dataTypeId: String` argument. While the constants for system types are device in `DataType.Type`, they are just strings.

While I haven't tried "chaining extensions", you should try to use `DataType.dataTypeId("other-extension-id", "other-type-id")` to build the string for other extensions for use in `StartStreaming`.
