### ISSUE TITLE
Problem with showmappage and zoom

### ISSUE THREAD

**Issue by lockevod** [hammerheadnav/karoo-ext#22]
I want to use the new Karoo Effect introduce in 1.1.2 (showmappage and zoom) but I cannot use any one (no effects) if I try with Marklap, performhardwareaction, etc all are working fine. I think I have only the problem with new ones effects

**Comment by lockevod** [comment]
I've udpated to 1.1.2 extension ;)

**Comment by brentnd** [comment]
@timklge is right. You can see in Releases 1.1.2 is still in pre-release. Once available on the Karoo side, it'll get updated to be latest release, taken out of alpha, and listed with the required KOS version.
