### ISSUE TITLE
View size always zero?

### ISSUE THREAD

**Issue by valterc** [hammerheadnav/karoo-ext#26]
Hi, trying to implement a custom graphical view. I'm using a graphical data type, defined in XML and in the extension types, I'm able to add the data type to profiles, but when the `startView` method of the `DataTypeImpl` is invoked, it seems that field `viewSize` of the [ViewConfig](https://github.com/hammerheadnav/karoo-ext/blob/ad7b4e5c7adea6b5d97a81606d6f66a75be9f9b3/lib/src/main/kotlin/io/hammerhead/karooext/models/ViewConfig.kt#L34C1-L37C34) always contain a pair of zero values.

The `gridSize` appears correct, based on the data type profile layout, but the `viewSize` does not reflect that. Could you double check if that works correctly? I could be doing something wrong.

Using version karoo-ext 1.1.2 and Karoo 1.527.2014

**Comment by brentnd** [comment]
There's a fix for this mentioned in #16 that will be available in the next Karoo release (`1.535.2029`). This will be noted when 1.1.2 is taken out of pre-release.

**Comment by valterc** [comment]
Missed that one fix on the PR notes! Thank you 🙂
