### ISSUE TITLE
Effect to request ANT

### ISSUE THREAD

**Issue by valterc** [hammerheadnav/karoo-ext#8]
Hi, I see there's an effect [RequestBluetooth](https://github.com/hammerheadnav/karoo-ext/blob/b0e167d5887cfe34cef3a980097b5df2e31cf2b4/lib/src/main/kotlin/io/hammerhead/karooext/models/KarooEffect.kt#L110C1-L110C29) that ensures that Bluetooth will be enabled, so an app can use Bluetooth even if Karoo OS is not using any Bluetooth connection. 

Can a similar new effect be added to request that ANT is enabled in the same circumstances? Or is it assumed that ANT is always enabled and available for any app using extensions (even when Karoo is not using any ANT sensor)?

Thank you.

**Comment by brentnd** [comment]
The nRF chip for ANT has a few other functions. On the new Karoo, the nRF chip is never turned off but on K2, if there are no ANT+ sensors in the Hammerhead sensors list _and_ no phone is paired, the radio is optimized to shut off. Therefore, it does make sense to add `RequestANT` like you suggest. I'll capture this as a new effect to implement.
